name: Release
on:
  issue_comment:
    types: [ created ]
jobs:
  build_and_release:
    name: Build and release
    runs-on: ubuntu-22.04
    if: contains(github.event.comment.body, '/release-action')
    steps:
      - name: Prepare devkitPro environment
        run: |
          sudo apt-get update && sudo apt-get install -y wget sudo libxml2 xz-utils lzma build-essential haveged python3 python3-pip lz4 zip
          sudo haveged &
          sudo touch /trustdb.gpg
          sudo update-alternatives --install /usr/bin/python python /usr/bin/python3.10 1
          pip install lz4
          sudo apt-get install -y apt-transport-https
          if [ ! -f /usr/local/share/keyring/devkitpro-pub.gpg ]; then
            sudo mkdir -p /usr/local/share/keyring/
            sudo wget -O /usr/local/share/keyring/devkitpro-pub.gpg https://apt.devkitpro.org/devkitpro-pub.gpg
          fi
          if [ ! -f /etc/apt/sources.list.d/devkitpro.list ]; then
              sudo echo "deb [signed-by=/usr/local/share/keyring/devkitpro-pub.gpg] https://apt.devkitpro.org stable main" | sudo tee /etc/apt/sources.list.d/devkitpro.list
          fi
          sudo apt-get update
          sudo apt-get install -y devkitpro-pacman
          sudo dkp-pacman -Sy && sudo dkp-pacman --noconfirm -Syu
          sudo dkp-pacman --noconfirm -S devkitA64 libnx switch-tools switch-curl switch-bzip2 switch-freetype switch-libjpeg-turbo switch-libwebp switch-sdl2 switch-sdl2_gfx switch-sdl2_image switch-sdl2_ttf switch-zlib switch-libpng switch-mesa general-tools switch-portlibs switch-dev switch-glm devkitARM devkitarm-rules hactool
        shell: bash
      - name: Update latest libnx
        run: |
          export DEVKITPRO=/opt/devkitpro
          git clone --recurse-submodules https://github.com/zdm65477730/libnx.git
          cd libnx
          make -j$(nproc)
          sudo mkdir -p ${DEVKITPRO}/libnx
          cd nx
          tar --exclude=*~ -cjf libnx.tar.bz2 include lib default_icon.jpg switch_rules switch.ld switch.specs -C external/bsd include
          sudo tar -xf libnx.tar.bz2 -C ${DEVKITPRO}/libnx --overwrite
        shell: bash
      - name: Checkout latest code
        uses: actions/checkout@v4.1.1
        with:
          ref: master
          clean: true
          fetch-depth: 0
          fetch-tags: true
      - name: Setup ENV parameters
        run: |
          commit=$(echo "$(git rev-parse --short=9 HEAD)")
          echo "COMMIT=${commit}" >> "${GITHUB_ENV}"
          VER_FILE=Versions.inc
          VERSION_HEKATE=$(awk '/^BLVERSION_MAJOR/{print $3}' $VER_FILE).$(awk '/^BLVERSION_MINOR/{print $3}' $VER_FILE).$(awk '/^BLVERSION_HOTFX/{print $3}' $VER_FILE)
          VERSION_NYX=$(awk '/^NYXVERSION_MAJOR/{print $3}' $VER_FILE).$(awk '/^NYXVERSION_MINOR/{print $3}' $VER_FILE).$(awk '/^NYXVERSION_HOTFX/{print $3}' $VER_FILE)
          echo "TAG=v${VERSION_HEKATE}-CN" >> "${GITHUB_ENV}"
          echo "RELEASE_NAME=hekate v${VERSION_HEKATE} & Nyx v${VERSION_NYX} CN" >> "${GITHUB_ENV}"
        shell: bash
      - name: Build
        run: |
          export DEVKITPRO=/opt/devkitpro
          export DEVKITARM=/opt/devkitpro/devkitARM
          make -j$(nproc)
        shell: bash
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: hekate-release-artifacts
          path: ./output/nyx.bin
      - name: Create release
        uses: ncipollo/release-action@v1.14.0
        with:
          artifacts: "nyx.bin"
          allowUpdates: yes
          tag: "${{ github.TAG }}"
          commit: "${{ github.COMMIT }}"
          prerelease: false
          name: "${{ github.RELEASE_NAME }}"
